version: '2.1'

services:
  blog:
    image: blog
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    volumes:
      - .:/app
    command: vuepress dev --host 0.0.0.0